### ISSUE TITLE
ReferenceError: self is not defined - Issue with whatwg-fetch when using the core lib with Node.js

### ISSUE THREAD

**Issue by adnanrahic** [statsbotco/cube.js#1]
The core library is not compatible with Node.js because of the `whatwg-fetch` module. I'd suggest moving to an [isomorphic alternative](https://github.com/matthew-andrews/isomorphic-fetch) that works with both browsers and server.

**Comment by adnanrahic** [comment]
Here's another viable option, [fetch-ponyfill](https://github.com/qubyte/fetch-ponyfill).

**Comment by paveltiunov** [comment]
Hey @adnanrahic ! I think it makes sense to use isomorphic-fetch. Also continuous retry logic should be disabled as well.

**Comment by superzadeh** [comment]
Also running into this while using Cube.js with Next.js. Pages have SSR enabled by default, and loading Cube.js becomes very tricky.

**Comment by paveltiunov** [comment]
@superzadeh Hey Charles! We just replaced `whatwg-fetch` with `isomorphic-fetch` in 0.7.3. Could you please try?

**Comment by superzadeh** [comment]
Awesome! just upgraded and it works flawlessly; server-side rendered charts, ❤
Thank you so much, so far I'm really loving the project 👍

**Comment by paveltiunov** [comment]
@superzadeh Hey Charles! Thanks for feedback! It's very interesting how you're using Next.js together with cube.js. Would love if you have a chance to write some tutorial blog post about that. Please reach me out in our [Slack](https://cubejs-community.herokuapp.com/) if you have some spare time.
