### ISSUE TITLE
add core-js dependency to @cubejs-client/react

### ISSUE THREAD

**Issue by ferndopolis** [statsbotco/cube.js#105]
**Describe the bug**
On our project we have updated babel to latest 7.4.0 which also change core-js to 3.0.0. With this change we are unable to complete our build because the ```@cubejs-client/react``` package which requires ```core-js: ^2.5.3``` ends up resolving with version ```3.0.0``` version of core-js.  The build fails throwing several "Module not found" errors like the one below. 

```ERROR in [repo-name]/node_modules/@cubejs-client/react/dist/cubejs-react.js
Module not found: Error: Can't resolve 'core-js/modules/web.dom.iterable' in '[repo-name]/node_modules/@cubejs-client/react/dist'
 @ [repo-name]/node_modules/@cubejs-client/react/dist/cubejs-react.js 10:0-43
 ...
 ...
 ...
```

To resolve this issue I forked the repo and added ```"core-js": "^2.5.3"``` to the ```@cubejs-client/react``` package as a dependency.  Then linked using ```yarn link``` on my project and the build worked!

https://github.com/shippabo/cube.js/commit/25f4aa1d1fc268f9b7f619beb3d56aa8702521ee

I would like to add this commit to the @cubejs-client/react package in PR.  Also I think it would be best to specify core-js dependency in all packages within @cubejs-client since it is required by babel and with mono repo its best to specify the dependency and not rely on the ```@cubejs-clent/core```

**Version:**
0.8.4

**Comment by paveltiunov** [comment]
@ferndopolis Hey Fernando! Thanks for posting this. Yeah. Adding this depend seems right to me. Could you please provide PR if you already did it? Thanks!

**Comment by ferndopolis** [comment]
ok i submitted it https://github.com/statsbotco/cube.js/pull/107
and do you want me to do the same for all the other packages?
