### ISSUE TITLE
Add option to run in production without redis

### ISSUE THREAD

**Issue by KnoxZZ** [statsbotco/cube.js#110]
It would be nice to be able to run cubejs in production mode without redis, especially when the datasets used are not massive.

**Comment by paveltiunov** [comment]
@KnoxZZ Hey Kalle! Thanks for posting this. There're several places that control Redis usage:
https://github.com/statsbotco/cube.js/blob/50f1bbb7aac34ae7c4fd82a86ecee8506b17f4ea/packages/cubejs-query-orchestrator/orchestrator/QueryQueue.js#L28
https://github.com/statsbotco/cube.js/blob/9d8b611a1d0cc4434e9d4288a634c0cdb0bc0d80/packages/cubejs-query-orchestrator/orchestrator/QueryCache.js#L14
https://github.com/statsbotco/cube.js/blob/032f588b54a0da7d541e31dd85135d17bd991cd9/packages/cubejs-query-orchestrator/orchestrator/PreAggregations.js#L375
I think it should be some `CubejsServerCore` option probably with some default initialized by ENV variable.

**Comment by paveltiunov** [comment]
Either `CUBEJS_CACHE_AND_QUEUE_DRIVER=memory` or `CUBEJS_CACHE_AND_QUEUE_DRIVER=redis` in env can be provided to override default behaviour.
