### ISSUE TITLE
Add option to reduce or eliminate the caching layer

### ISSUE THREAD

**Issue by albertkim** [statsbotco/cube.js#112]
**Is your feature request related to a problem? Please describe.**

When looking at constantly changing data, the numbers shown could be delayed for up to 2 minutes. 2 minutes seems rather arbitrary, and depending on the data, may not be acceptable for clients.

**Describe the solution you'd like**

I would like an option to configure or remove the query caching.

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered.[

The only other option I can think of is to fork the repository to adjust the core code. Pavel has mentioned in slack that the caching delay code lives here: https://github.com/statsbotco/cube.js/blob/9d8b611a1d0cc4434e9d4288a634c0cdb0bc0d80/packages/cubejs-query-orchestrator/orchestrator/QueryCache.js#L183

**Additional context**

**Comment by albertkim** [comment]
For anyone else reading this, here's another idea to get over this:

In my application, I have the following:

```
const endDateString = moment(this.props.endDate).isSame(moment(), 'day') ? new Date().toISOString() : moment(this.props.endDate).format('YYYY-MM-DD')
```

What this allows me to do is pass in a different endDate string, which should hopefully bypass the caching layer and disable it for queries requesting today's data.

**Comment by paveltiunov** [comment]
@albertkim Hey Albert! Thanks for posting this! Could you please elaborate a little bit on behaviour you're trying to achieve: is this just you're trying to get something like 30 seconds freshness? Do you have real time data and some client timer that refreshes every 30 seconds?

**Comment by albertkim** [comment]
I operate a POS application, where customers expect to see their data within latest 1 minute when they look at their reporting dashboard. I'm looking to use Cube.js as a replacement for my old sql-based system.

**Comment by albertkim** [comment]
The thing is that historical data never changes, so I'm happy with caching there, but for requests that involve today, I effectively need to disable caching. I'm wondering if this is a use case that others might also run into.

**Comment by paveltiunov** [comment]
@albertkim Gotcha. So there're actually two things that would affect this behaviour. First one is `renewalThreshold` which you referenced. The second one is renew behaviour which will return cached results even if renewal is requested until new data is ready. I think it makes sense to try adjusting `renewalThreshold` first and see how it works for you. If it's not there's also `renewQuery` flag that we'd need to propagate to the API Gateway level.

**Comment by paveltiunov** [comment]
@albertkim I just added this option that can be used as
```
CubejsServerCore.create({
  orchestratorOptions: {
    queryCacheOptions: {
      refreshKeyRenewalThreshold: 30
    }
})
```

**Comment by albertkim** [comment]
@paveltiunov Thank you for this! However, I don't think this quite solves the use case. Here is what I went through with the latest 0.9.4 update.

1) I load a query
2) I add more data
3) I wait 10+ seconds (I set to to be 10)
4) I refresh the query
5) I see old data
6) I continue to see data for the next several refreshes until eventually see the new data

There is a the following in `QueryCache.js`: `const expireSecs = queryBody.expireSecs || 24 * 3600;`. I this related to the renewQuery you're talking about?

**Comment by albertkim** [comment]
I do see what you mean by returning a cached result while the renewal is happening in the background. A proposal could be that the client can pass in whether it wants a cached result or not - some time filters are very sensitive to cached results, whereas for older historical data, not much so.

**Comment by paveltiunov** [comment]
@albertkim Makes sense. Just published new version with `renewQuery` flag for query. Can be used like:
```
{
  measures: [...],
  dimensions: [...],
  renewQuery: true
}
```

**Comment by albertkim** [comment]
@paveltiunov Settle down! How can you guys be this responsive?

**Comment by paveltiunov** [comment]
@albertkim 😄We just here to help! Yep. `renewQuery: true` means orchestrator will wait for `refreshKey` to invalidate first and then wait for actual query invalidation if required.
