### ISSUE TITLE
QueryRenderer: "contains" filter does not work with SQL Server database

### ISSUE THREAD

**Issue by antoniablair** [statsbotco/cube.js#113]
**Describe the bug**
When using Microsoft SQL Server and cubejs-client/react, trying to use the "contains" operator in a `<QueryRenderer>` component results in a SQL error: `Error: Error: Incorrect syntax near 'ILIKE'.` 
I believe this would be resolved if the underlying SQL query used `LIKE` instead of `ILIKE`.

**To Reproduce**
1. Create a CubeJS project that uses a MSSQL database (`cubejs create <project name> -d mssql`). To reproduce the bug, you would need something to search through, such as a table containing a column of strings. Set up the relevant Cube schema to match the database. 
2. Start a development server and open up CubeJS in the browser. Go to "Explore".
3. Try to create a new chart by choosing a measure, then click filter > contains and type in a search term. 
4. You will see an error below where it would normally render a chart (see screenshot).

**Expected behavior**
Normally this would create a chart of objects that matched the search term.

**Screenshots**
![ILIKE-error](https://user-images.githubusercontent.com/7012513/58282924-121c4900-7d75-11e9-9683-6b52737ae2f3.PNG)

**Version:**
[e.g. 0.4.5]

**Additional context**
Example code snippet that illustrates the "contains" operator in QueryRenderer: 

```
          <QueryRenderer
            query={{
              measures: ["Events.uniqueSessionCount"],
              timeDimensions: [
                {
                  dimension: "Events.starttime"
                }
              ],
              dimensions: ["Events.action"],
              filters: [
                {
                  dimension: "Events.action",
                  operator: "contains",
                  values: ["Question"]
                }
              ]
            }}
            cubejsApi={cubejsApi}
            render={renderChart(lineRender)}
          />
```

**Comment by paveltiunov** [comment]
@antoniablair Hey Antonia! Thanks for posting this one! I can confirm it just wasn't implemented for MSSQL.

**Comment by paveltiunov** [comment]
@antoniablair Just released it. Could you please check and let me know if it works for you?

**Comment by antoniablair** [comment]
@paveltiunov Works perfectly, thanks!
