### ISSUE TITLE
Connecting Json based data to cubejs

### ISSUE THREAD

**Issue by sameerkhan662** [statsbotco/cube.js#114]
I want to connect my cubejs server for data to json to achieve schema operation.

I just want cubejs to understand json instead to connect directly to db

**Comment by paveltiunov** [comment]
Hey @sameerkhan662 ! Thanks for posting this! Could you please provide an example of what you're trying to achieve?

**Comment by paveltiunov** [comment]
@sameerkhan662 What's the DB you're using here? Is it Cassandra? Or just JSON files?

**Comment by sameerkhan662** [comment]
Though we are using time series database and I don't think we have option for this here in cubejs but Json files can be connected is there any option for that?

**Comment by paveltiunov** [comment]
@sameerkhan662 Yeah. You can do that. Cube.js works with Athena which is capable of querying raw JSON files. Please follow this guide to setup it: https://docs.aws.amazon.com/athena/latest/ug/querying-JSON.html

**Comment by paveltiunov** [comment]
Hey @sameerkhan662 ! Could you please provide some feedback on it if it works for you? Thanks!
