### ISSUE TITLE
Use multiple date ranges in the same query

### ISSUE THREAD

**Issue by codejunior12** [statsbotco/cube.js#115]
I would like to be able to use multiple date ranges in the same query. In my case I would like to display the total number of products sold during two separate periods.
(ex if 50 are sold during the first period and 30 during the second period, 80 would be displayed)

Something like that :
`query={{
measures: ["FinalData.count"],
                timeDimensions: [
                  {
                    dimension: "FinalData.date",
                    dateRange: ["2019-01-01", "2019-06-30"],
                    granularity: "month"
                  },
                  {
                    dimension: "FinalData.date",
                    dateRange: ["2018-01-01", "2018-06-30"],
                    granularity: "month"
                  }
                ]
              }}`

**Comment by paveltiunov** [comment]
Hey @codejunior12 ! Thanks for posting this! Very interesting idea. Could you please elaborate a little bit on what you expect to see by issuing such query? Two line charts with year-over-year comparison?

**Comment by codejunior12** [comment]
In my case I am just displaying a number in a Bootstrap Card (number of products sold). The user is manually selecting the months of his choice on a months timeline (he can select multiple months, consecutive or not. Then the user should be able to see the total number of products sold based on his selection.

**Comment by paveltiunov** [comment]
@codejunior12 Very interesting use case. Is it always month granularity? No way to select specific dates?

**Comment by paveltiunov** [comment]
@codejunior12 If I get you right I think you can create dimension which formats time in `YYYY-MM` format and then put the multiple filter on it:
```
query={{ 
  measures: ["FinalData.count"], 
  filters: [{
    dimension: "FinalData.yearMonth",
    operator: "equals",
    values: ["2018-01", "2018-02", "2018-03", "2018-04", "2018-05", "2018-06", "2019-01", "2019-02", "2019-03", "2019-04", "2019-05", "2019-06"]
  }],
  timeDimensions: [{ dimension: "FinalData.date", granularity: "month" }] 
}}
```
If you can tell what DB do you use I'll be able to guide you how to setup `FinalData.yearMonth` dimension.

**Comment by codejunior12** [comment]
Thank you for your help ! I use MongoDB. Yes for now the user can only select months.

**Comment by paveltiunov** [comment]
@codejunior12 So it should be something like:
```
...
dimensions: {
  ...,
  yearMonth: {
    sql: `DATE_FORMAT(${date}, '%Y-%m')`,
    type: `string`
  }
},
...
```
Please let me know if it works for you.

**Comment by codejunior12** [comment]
Sorry for the late reply, yes it worked, thank you :) The only issue is that the page crashes when no data matches the selected month. Any idea why? I use react.

**Comment by paveltiunov** [comment]
Hey @codejunior12 ! Are there any error messages?

**Comment by codejunior12** [comment]
I am getting the following error message : TypeError: Cannot read property 'FinalData.count' of undefined

**Comment by paveltiunov** [comment]
@codejunior12 Is this browser error or server-side? Would you mind to post stack trace of this error as well?

**Comment by codejunior12** [comment]
@paveltiunov It's a browser error, here is the stack trace : 
```
Uncaught TypeError: Cannot read property 'FinalData.count' of undefined
    at renderSingleValue (KpiDashboard.js:34)
    at render (KpiDashboard.js:132)
    at Object.render (Chart.js:29)
    at QueryRenderer.render (cubejs-react.js:235)
    at finishClassComponent (react-dom.development.js:15320)
    at updateClassComponent (react-dom.development.js:15275)
    at beginWork (react-dom.development.js:16265)
    at performUnitOfWork (react-dom.development.js:20285)
    at workLoop (react-dom.development.js:20326)
    at HTMLUnknownElement.callCallback (react-dom.development.js:147)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:196)
    at invokeGuardedCallback (react-dom.development.js:250)
    at replayUnitOfWork (react-dom.development.js:19509)
    at renderRoot (react-dom.development.js:20439)
    at performWorkOnRoot (react-dom.development.js:21363)
    at performWork (react-dom.development.js:21273)
    at performSyncWork (react-dom.development.js:21247)
    at requestWork (react-dom.development.js:21102)
    at scheduleWork (react-dom.development.js:20915)
    at Object.enqueueSetState (react-dom.development.js:11596)
    at QueryRenderer.push../node_modules/react/cjs/react.development.js.Component.setState (react.development.js:336)
    at cubejs-react.js:171
```
I hope this helps.

**Comment by paveltiunov** [comment]
@codejunior12 seems like you copied this `renderSingleValue` code somewhere. So in your case you should guard it so it doesn't fail. Something like this:
```
resultSet.chartPivot()[0] && resultSet.chartPivot()[0][key]
```

**Comment by codejunior12** [comment]
@paveltiunov  Thank you so much!
