### ISSUE TITLE
Playground UI doesn't work after upgrade

### ISSUE THREAD

**Issue by avin3sh** [statsbotco/cube.js#116]
The dev server on release `0.9.11` does not work on the Firefox, more specifically `http://localhost:4000/#/dashboard` throws lots of `resource MIME type mismatch` errors in the browser console. 

However `http://localhost:4000/#/schema` page works just fine.

**Comment by paveltiunov** [comment]
@avin3sh Hey Avinesh! Thanks for posting this one! Could you please try to reset cache and refresh page?

**Comment by avin3sh** [comment]
Hi Pavel, Clearing the cache from the earlier version did resolve the issue. My bad I did not try it before.

**Comment by paveltiunov** [comment]
@avin3sh Hey Avinesh! Thanks for clarifying! I can confirm we have an issue with incorrect caching of index.html for playground so I guess we should leave this open.
