### ISSUE TITLE
statsbot working in slack

### ISSUE THREAD

**Issue by PVinay737** [statsbotco/cube.js#135]
/statsbot and /statsbot-goals not working . PFA screenshots

![errsb](https://user-images.githubusercontent.com/44138475/59566771-5227d080-9082-11e9-8b30-66ec157f5931.png)

The same error persists upon changing different accounts 

![errsbga](https://user-images.githubusercontent.com/44138475/59566772-5227d080-9082-11e9-96df-3e3a4c3e9362.png)

How to fix this ?

**Comment by PVinay737** [comment]
Will add doc/readme with installation guide in slack once this is fixed

**Comment by PVinay737** [comment]
Can I include a PR with installation guide in slack once this is fixed ?

**Comment by PVinay737** [comment]
Maybe a installation guide can help..

**Comment by paveltiunov** [comment]
@PVinay737 It's cube.js repository only for cube.js related issues. For Statsbot issues please contact support.
