### ISSUE TITLE
Missing link in docs

### ISSUE THREAD

**Issue by PVinay737** [statsbotco/cube.js#136]
Project link missing in e-commerce dashboard part

https://github.com/statsbotco/cube.js/blob/master/docs/Examples.md

Have a look at this 

[ecommerce-dashboard-react](https://github.com/statsbotco/cube.js/tree/master/examples/ecommerce-dashboard-react)

**Comment by paveltiunov** [comment]
Hey @PVinay737 ! Thanks for posting this! Yep. Seems like broken link. cc @keydunov

**Comment by keydunov** [comment]
@PVinay737 Thanks! Fixed by https://github.com/statsbotco/cube.js/commit/6a3b28519ec8efa46a4e82917a1331a00b34a41a#diff-264c74dad2b57eb2727e886603691967
