### ISSUE TITLE
Error connecting to mongodb

### ISSUE THREAD

**Issue by PVinay737** [statsbotco/cube.js#138]
**Describe the bug**
Error connecting mongodb and I find it to be a  duplicate of #24 but here its not postgres and I am not sure which one fixes the error 

**To Reproduce**
```
- Fetching DB schema

Cube.js Error ---------------------------------------

Error: connect ECONNREFUSED 127.0.0.1:5000
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)

```
Any suggestions ?

**Comment by paveltiunov** [comment]
Hey @PVinay737 ! On what port are you running your mongo BI server? Usually the port is 3307. Please see https://cube.dev/blog/building-mongodb-dashboard-using-node.js for more info.

**Comment by PVinay737** [comment]
Still the same error persists with port 3307 as well

**Comment by paveltiunov** [comment]
@PVinay737 Are you running mongo BI server? If yes, could you please provide its logs?

**Comment by PVinay737** [comment]
Working !

The issue arises when one does not start mongo BI server

**Comment by dharmdip** [comment]
Hi @paveltiunov, I am trying to get this running and stuck with an error. 

`Error: connect ETIMEDOUT
    at Connection._handleTimeoutError (/Users/devmachine/apps/cube/mongo-tutorial/node_modules/mysql2/lib/connection.js:178:17)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)`

**.env file configuration is here** 

`CUBEJS_DB_HOST=localhost
CUBEJS_DB_NAME=test
CUBEJS_DB_PORT=27017
CUBEJS_DB_TYPE=mongobi
CUBEJS_API_SECRET=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx`

I am trying to run with MongoDB Atlas then after tried with localhost setup, getting same error.

**Comment by dharmdip** [comment]
Hi @paveltiunov, 

it's working now, did't configure MongoBI with path and causing the issue.

**Comment by Matar91** [comment]
Hi @paveltiunov paveltiunov, same error for me:

```
Error: connect ECONNREFUSED 17x.xx.xx.13:3307
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1134:16)

```
I've tried different combinations for  .env configuration:

```
CUBEJS_DB_HOST=17x.xx.xx.13
CUBEJS_DB_NAME=PPCWebAPI
CUBEJS_DB_USER=root
CUBEJS_DB_PASS=xxxx
CUBEJS_DB_PORT=3307
CUBEJS_DB_TYPE=mongobi
CUBEJS_API_SECRET=xxx
```
The BI connector seems to work fine :

![image](https://user-images.githubusercontent.com/19257081/88076123-fa5b7300-cb79-11ea-9ddd-5185843b62b0.png)

**Comment by paveltiunov** [comment]
@Matar91 Your MongoBI is listening on loopback's 127.0.0.1 address and you're trying to connect using real network interface address.

**Comment by Matar91** [comment]
> @Matar91 Your MongoBI is listening on loopback's 127.0.0.1 address and you're trying to connect using real network interface address.

Thanks @paveltiunov, i managed to solve that problem but i still have this one everytime i try to upload a schema from the cube js playground:

![image](https://user-images.githubusercontent.com/19257081/91582470-270c6280-e950-11ea-9c41-4b9793525ad8.png)

BIconnector is setted on the correct ip (no localhost):
![image](https://user-images.githubusercontent.com/19257081/91582787-94b88e80-e950-11ea-8a4a-cc4b6fddaca2.png)

And the .env file its still the same..

**Comment by Matar91** [comment]
> @Matar91 Your MongoBI is listening on loopback's 127.0.0.1 address and you're trying to connect using real network interface address.

Thanks @paveltiunov i managed to solve the problem. The only problem left is when i connect to BI connector i get this 

![image](https://user-images.githubusercontent.com/19257081/91590668-00542900-e95c-11ea-966e-7d5d0b66fcd1.png)

I am using SSL certificate as you suggested here [](https://stackoverflow.com/questions/58868085/cube-js-error-ssl-is-required-when-using-cleartext-authentication-using-mongod)

**Comment by Matar91** [comment]
> > @Matar91 Your MongoBI is listening on loopback's 127.0.0.1 address and you're trying to connect using real network interface address.
> 
> Thanks @paveltiunov i managed to solve that problem. The only problem left with handshake, happens once Cube Js connects with BIconnector:
> 
> ![image](https://user-images.githubusercontent.com/19257081/91590668-00542900-e95c-11ea-966e-7d5d0b66fcd1.png)
> 
> I am using SSL certificate as you suggested here [https://stackoverflow.com/questions/58868085/cube-js-error-ssl-is-required-when-using-cleartext-authentication-using-mongod](url)

Solved, had to add this in cube.js .env file:

`CUBEJS_DB_SSL=true
CUBEJS_DB_SSL_REJECT_UNAUTHORIZED=false
`

**Comment by FiveOFive** [comment]
I got hit with the ECONNREFUSED error for MongoDB because I was running cube js on my local Mac in a Docker container and trying to connect to mongodb bi locally at 127.0.0.1. Needed to use host.docker.internal - https://docs.docker.com/docker-for-mac/networking/
