### ISSUE TITLE
Tutorial example typo - Direction of Joins

### ISSUE THREAD

**Issue by bonchef** [statsbotco/cube.js#139]
https://cube.dev/docs/direction-of-joins . From Orders to Customers I believe the relationship should be 'belongsTo', not 'hasMany'.

**Comment by paveltiunov** [comment]
@bonchef Hey Tim! Thanks for posting this! cc @keydunov

**Comment by keydunov** [comment]
@bonchef Thanks! Fixed by https://github.com/statsbotco/cube.js/commit/fd3ca21fac810d44f91e782d6bf22ce75e66ac93
