### ISSUE TITLE
Option to configure cube to use independent Redis

### ISSUE THREAD

**Issue by brentcodes** [statsbotco/cube.js#146]
It would be useful  to be able to configure cube to be able to use an independent Redis instance, either in addition to, or in place of its current solution.

This would allow me to have a large Redis instance to always ready to deal with large datasets, while scaling cube instances to meet the current volume of requests.

However, if there was a reason you decided to go with an integrated Redis instance, it would be nice to know the reasoning behind the decision. Thanks :)

**Comment by paveltiunov** [comment]
Hey @brentcodes ! Thanks for posting this one! Could you please elaborate a little bit what do you mean by independent Redis instance?

**Comment by brentcodes** [comment]
@paveltiunov Thanks for your quick response, it is appreciated!

I mean, if I have a redis instance already running on a different server, I would like to be able to configure cube to point to that other server, the same way I can configure it to point to a database.

Sorry I was not more clear.

**Comment by paveltiunov** [comment]
@brentcodes You actually can do this using `REDIS_URL`: https://cube.dev/docs/deployment#top

**Comment by brentcodes** [comment]
Ah, sorry, I did not see it in the .env file. Sorry about that

**Comment by paveltiunov** [comment]
@brentcodes No probs! 🙌 Please let me know if there're any other questions.

**Comment by brentcodes** [comment]
@paveltiunov  Yes actually; are there any other config options for Redis, such pointing to multiple instances for high availability or sharding?

**Comment by paveltiunov** [comment]
@brentcodes Right now there's no way to pass many cluster servers to connect to at once as it's not part of URI spec AFAIK. There're `RedisCacheDriver` and `RedisQueueDriver` that are responsible for accessing redis. You might want to override those and use something like https://github.com/gosquared/redis-clustr there.

**Comment by brentcodes** [comment]
@paveltiunov Thanks again for your help. Would you be interested in a new contributor trying to add this feature?

**Comment by paveltiunov** [comment]
@brentcodes Yep. Sure! It would be great if you can contribute optional cluster versions of `RedisCacheDriver` and `RedisQueueDriver`.

**Comment by keeganmccallum** [comment]
I've been able to make cubejs work with a redis sentinel by replacing RedisFactory.js with: 
```
const Redis = require('ioredis');

module.exports = function createRedisClient(url) {
    // map exec responses to match node-redis: https://github.com/luin/ioredis/wiki/Migrating-from-node_redis
    Redis.Pipeline.prototype.execAsync = function () {
        return new Promise((resolve, reject) => {
            // rely on scope
            this.exec(function (err, res) {
                console.log(err, res)
                if (err) return reject(err);
                return resolve(res.map((nestArr) => nestArr[1]));
            })
        })
    };
    const [host, port] = url.replace('redis://', '').split(':');
    let options = {
        sentinels: [{ host, port }],
        name: "mymaster"
    };

    if (process.env.REDIS_TLS === 'true') {
        options.tls = {};
    }

    if (process.env.REDIS_PASSWORD) {
        options.password = process.env.REDIS_PASSWORD;
    }

    const client = new Redis(options);

    ['brpop', 'del', 'get', 'hget', 'rpop', 'set', 'zadd', 'zrange', 'zrangebyscore', 'keys'].forEach(
        k => {
            client[`${k}Async`] = client[k];
        }
    );

    return client;
};
```

Would want to add better config to support more of ioredis's options, as well as support non-sentinel but thought I'd share as a starting point for someone
