### ISSUE TITLE
`Dashboard` Errors to generated schema

### ISSUE THREAD

**Issue by PVinay737** [statsbotco/cube.js#149]
**To Reproduce**
Generated schema not working 
![generate](https://user-images.githubusercontent.com/44138475/60463445-a37eb500-9c69-11e9-9dab-39a213e1e4b2.png)

Upon checking the dashboards the following error comes up

```
Error: Error: Compile errors: Syntax error during 'abc.js' parsing: Unexpected token, expected , (2:28)


```

**Comment by paveltiunov** [comment]
@PVinay737 Thanks for posting this one! It was fixed in https://github.com/statsbotco/cube.js/releases/tag/v0.10.9. Could you please upgrade and check?

**Comment by PVinay737** [comment]
It works !

Can we have the visualizations rendered of the generated schema instead of this displaying ?

![dashlog](https://user-images.githubusercontent.com/44138475/60485291-1a439e80-9cba-11e9-8c89-847f64d851b6.png)

**Comment by paveltiunov** [comment]
@PVinay737 Yep. Sure! Please use Explore to build chart of an interest and use 'Add to dashboard' button to add it to dashboard.
