### ISSUE TITLE
Add dependency "@cubejs-backend/server-core" installs "@cubejs-backend"

### ISSUE THREAD

**Issue by dtslvr** [statsbotco/cube.js#16]
When I run `yarn add @cubejs-backend/server-core` I get a `@cubejs-backend` in my `node_modules` folder.

I would expect the following modules instead:
* `node_modules/@cubejs-backend/server-core`
* `node_modules/@cubejs-backend/api-gateway` (dependency of `server-core`)
* `node_modules/@cubejs-backend/query-orchestrator` (dependency of `server-core`)
* `node_modules/@cubejs-backend/schema-compiler` (dependency of `server-core`)

**Comment by paveltiunov** [comment]
@dtslvr Thanks for posting this! 

Do you mean you see `@cubejs-backend` subdirectory and expect to see flat directory structure? Or you can't find `api-gateway`, `query-orchestrator` and `schema-compiler` dependencies in your `node_modules` at all after `server-core` install?

**Comment by dtslvr** [comment]
I'm very sorry. I got a module not found error, but it turned out it was not installed in that project :man_facepalming:
It works as expected, issue can be closed.

**Comment by paveltiunov** [comment]
Good to hear that! 🙌
