### ISSUE TITLE
Cube.js Error while connecting to postgres db

### ISSUE THREAD

**Issue by pramur81** [statsbotco/cube.js#24]
Hi,

I m trying to connect to postgres db (which comes with Tableau installation). I am able to connect to this postgres db from tableau whereas when I tried to establish connectivity from cubejs I got below error message
Error: connect ECONNREFUSED XXX.XX.XXX.XX:5432  at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1113:14)

Please note the tableau server which has postgres db is SSL enabled. I m not sure whether that is the problem.

Please help fix this issue. I m facing same issue while connecting to mongoDB via mongoDB BI Connector

Thanks
Murugan

**Comment by paveltiunov** [comment]
Hi @pramur81 ! Thanks for posting this!

Yep. It can be an issue actually. Could you please try passing ssl option directly to driver?
Like this:
```
const PostgresDriver = require('@cubejs-backend/postgres-driver');
const server = new CubejsServer({
  driverFactory: () => new PostgresDriver({ ssl: true })
});
```
You can learn more about pg ssl here: https://node-postgres.com/features/ssl

**Comment by pramur81** [comment]
Thanks Pavel for your reply. Do I need to go to this path

\cube.js-master\cube.js-master\hello-world\node_modules\@cubejs-backend\postgres-driver\driver\PostgresDriver.js and edit this file with the code that you posted in your reply?

Below is the code in this file...pls let me know where exactly I need to add the code for ssl? Also do I need to point to certificate file too (.pem file)

const BaseDriver = require('@cubejs-backend/query-orchestrator/driver/BaseDriver');
const { Pool } = require('pg');

class PostgresDriver extends BaseDriver {
  constructor(config) {
    super();
    this.config = config || {};
    this.pool = new Pool({
      max: 8,
      idleTimeoutMillis: 30000,
      host: process.env.CUBEJS_DB_HOST,
      database: process.env.CUBEJS_DB_NAME,
      port: process.env.CUBEJS_DB_PORT,
      user: process.env.CUBEJS_DB_USER,
      password: process.env.CUBEJS_DB_PASS,
      ...config
    });
    const self = this;
    this.pool.on('error', (err) => {
      console.log(`Unexpected error on idle client: ${err.stack || err}`); //TODO
    });
  }

Below are the details in my .env file..is there a way I can add ssl=true in env file?
CUBEJS_DB_HOST=XXX.XX.XXX.XX
CUBEJS_DB_NAME=workgroup
CUBEJS_DB_USER=readonly
CUBEJS_DB_PASS=XXXXX
CUBEJS_DB_TYPE=postgres
CUBEJS_API_SECRET=XXXX

**Comment by pramur81** [comment]
Also I just tried to connect to postgres DB which is not SSL enabled but I still get same error
Error: connect ECONNREFUSED XXX.XX.XXX.XX:5432 at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1113:14)

**Comment by paveltiunov** [comment]
@pramur81 I actually meant you can add this code to your `index.js` that's generated when you create your app using Cube.js CLI.

Do you have `psql` installed locally? Could you please check that these addresses are accessible through `psql`?

**Comment by paveltiunov** [comment]
Hi @pramur81 ! Did you have a chance to resolve this issue?

**Comment by sam-som** [comment]
This is for anyone who see this issue.
If your `cube.js` is in docker and your postgres is on host, you need to use `CUBEJS_DB_HOST=host.docker.internal`

**Comment by shiv-u** [comment]
In Ubuntu use the following command if you're using Docker - 
``` 
sudo docker run -p 4000:4000 --network host\
  -v ${PWD}:/cube/conf \
  -e CUBEJS_DEV_MODE=true \
  cubejs/cube```
