### ISSUE TITLE
Add ESLint, any other auto-formatting config

### ISSUE THREAD

**Issue by dylburger** [statsbotco/cube.js#25]
Per our Slack conversation, this ticket is a placeholder for the work needed to move any existing ESLint, Prettier, or any other dot-files / config related to linting and formatting into this public Github repo.

Let me know if I can be of any help on this - happy to!

**Comment by paveltiunov** [comment]
@dylburger added ESLint to `cubejs-cli`. I think all backend packages should reuse this config. Client will have different one though. 

Need to spread this config to other packages.

**Comment by matthewstrasiotto** [comment]
Related (Client linting support) #3680
