### ISSUE TITLE
Giving me weird error

### ISSUE THREAD

**Issue by ankit6373** [statsbotco/cube.js#30]
![fireshot capture 35 - 0pwy35x5rv - codesandbox - https___codesandbox io_s_0pwy35x5rv](https://user-images.githubusercontent.com/18262572/53322420-62fcdc80-3901-11e9-9497-c7085083e290.png)

I have created 2 Schemas/Tables Orders and Users. In index.js file I am trying to render User's table attributes. I don't have this 'status' attribute in any of my sql table and schema. Why I am getting this even though,I have no where mentioned 'status' and I am trying to render Users schema.

This is my index.js File 

     `const CubejsServer = require('@cubejs-backend/server');
      import cubejs from '@cubejs-client/core';
      import Chart from 'chart.js';
      import chartjsConfig from './toChartjsData';
 
       const cubejsApi = cubejs('eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpIjozODU5NH0.5wEbQo- 
       VG2DEjR2nBpRpoJeIcE_oJqnrm78yUo9lasw'); 
 
       const server = new CubejsServer();

      const resultSet = await cubejsApi.load({
          measures: ['Users.paying'],
          timeDimensions: [{
            dimension: 'Users.createdAt',
           dateRange: ['2018-01-01', '2018-07-31'],
           granularity: 'month'
        }]
     })
     const context = document.getElementById("myChart");
     new Chart(context, chartjsConfig(resultSet));

     server.listen().then(({ port }) => {
     console.log(`ðŸš€ Cube.js server is listening on ${port}`);
     });`

**Comment by paveltiunov** [comment]
Hi ankit6373! Thanks for posting this!

So everything related to `@cubejs-client` is considered client code and should be executed by browser. We have an issue for server side rendering as well but it isn't supported yet: #1 .

So you should put this client code from `index.js` to your code sandbox screenshot of which you attached. Please let us know how it goes.

**Comment by paveltiunov** [comment]
@ankit6373 would love to hear from you about this. Closing for now due to inactivity
