### ISSUE TITLE
Allow hot reload for cubes. Feature request

### ISSUE THREAD

**Issue by Kylia669** [statsbotco/cube.js#37]
Now server starts and loads all cubes from schema folder ( or another folder )
when I change my schema I need to restart start server. 

hot reload feature:
- when the server can`t find some dimension or measure or segment, it can reload cube again and check is it present in the cube. do just 1 reload and return validation result when can`t find required property. 

profit:
it`ll allow changing schema in runtime.

**Comment by paveltiunov** [comment]
@Kylia669 Thanks for posting this! This feature definitely should be there.

**Comment by giacomochiarella** [comment]
@Kylia669 @paveltiunov does it work for you? I'm using docker image cubejs/cube:v0.34.7 with models stored in host folder attached to the container as a volume and it does not work (I can see the new files/changes in the docker container)
