### ISSUE TITLE
Validate for empty query object

### ISSUE THREAD

**Issue by keydunov** [statsbotco/cube.js#39]
Now, if you pass empty query it will give a weird error. Query needs to be validated.

**Comment by manojown** [comment]
@keydunov can you please elaborate this issue like what error you get .

**Comment by keydunov** [comment]
@manojown Sure! If one sends a request to Cube.js with empty `query` params it returns 500 error. I think API gateway should validate the incoming `query` and return the valid error. Please see the screenshot from Postman with this error -

<img width="958" alt="Screen Shot 2019-04-01 at 12 08 24 PM" src="https://user-images.githubusercontent.com/1618877/55316410-fe401f00-5476-11e9-9d97-d9417fd17ccf.png">

**Comment by manojown** [comment]
@paveltiunov what is better way to do that . 
1 . verify empty query object at api gateway level(if query is empty than its avoid all further server execution)  ?
**OR**
2.  go through all crash and fix those by some conditions ?

**Comment by paveltiunov** [comment]
@manojown Hey Manoj! That's great question! I think it should be on `api-gateway` level as all validation is done there.
