### ISSUE TITLE
Disable authentication check

### ISSUE THREAD

**Issue by dtslvr** [statsbotco/cube.js#42]
As we are implementing our own authentication middleware, it would be great to disable the authentication check in `@cubejs-backend/api-gateway`.

I could imagine something like this:

```
import * as CubejsServerCore from "@cubejs-backend/server-core";

const config = {
  ...
  security: false
};
const core = CubejsServerCore.create(config);
```

What do you think?

**Comment by paveltiunov** [comment]
@dtslvr I think it makes sense to add such behavior. The only thing: API gateway requires user context to get user info from. Probably the best way is to extract auth middleware which sets user context and let users override it.

**Comment by dtslvr** [comment]
@paveltiunov Yes, overriding sounds reasonable.

**Comment by dtslvr** [comment]
Great work! Now I can override it via

```
const config = {
  checkAuthMiddleware: ({ next }) => {
    return next && next();
  }
};

CubejsServerCore.create(config);
```
