### ISSUE TITLE
Fix dependency warning in schema compiler (joi)

### ISSUE THREAD

**Issue by dtslvr** [statsbotco/cube.js#47]
I get the following warning for `@cubejs-backend/server-core`: `@cubejs-backend/schema-compiler` > `joi@10.6.0`: This version is no longer maintained. Please upgrade to the latest version.

**Comment by paveltiunov** [comment]
@dtslvr Yeah. Definitely need to upgrade.

**Comment by manojown** [comment]
Can i take a initiative for this update . ?

**Comment by paveltiunov** [comment]
@manojown Hey Manoj! Yep sure! It would be great!
