### ISSUE TITLE
issue with schema generator for mongobi 

### ISSUE THREAD

**Issue by krunalsabnis** [statsbotco/cube.js#49]
**1. Using mysql driver for MongoDB BI**

For MongoDB BI generate schema file contains DB name as prefix in query which causes an issue.
For Example: 
Schema file for TableOne generate  SQL = > sql: `SELECT * FROM DBANE_PREFIX.TableOne`,
If DBANE_PREFIX is removed it works fine.

**2. Using monogbi driver for MongoDB BI**

Schema file still contains PREFIX however it seems server can not transform the schema. (May be mongobi handling needs to be done for rendering on UI ).
 In this case error as below 

Error: Error: Compile errors: TypeError: Cannot read property 'aliasName' of null at CubeToMetaTransformer.measureConfig (/home/kru/antphant/git/cube.js/p1/node_modules/@cubejs-backend/schema-compiler/compiler/CubeToMetaTransformer.js:105:31) at config.measures.R.compose.R.map (/home/kru/antphant/git/cube.js/p1/node_modules/@cubejs-backend/schema-compiler/compiler/CubeToMetaTransformer.js:32:40) at _map (/home/kru/antphant/git/cube.js/p1/node_modules/@cubejs-backend/schema-compiler/node_modules/ramda/src/internal/_map.js:6:19) at map (/home/kru/antphant/git/cube.js/p1/node_modules/@cubejs-backend/schema-compiler/node_modules/ramda/src/map.js:57:14) at /home/kru/antphant/git/cube.js/p1/node_modules/@cubejs-backend/schema-compiler/node_modules/ramda/src/internal/_dispatchable.js:39:15 at /home/kru/antphant/git/cube.js/p1/node_modules/@cubejs-backend/schema-compiler/node_modules/ramda/src/internal/_curry2.js:20:46 at f1 (/home/kru/antphant/git/cube.js/p1/node_modules/@cubejs-backend/schema-compiler/node_modules/ramda/src/internal/_curry1.js:17:17) at /home/kru/antphant/git/cube.js/p1/node_modules/@cubejs-backend/schema-compiler/node_modules/ramda/src/internal/_pipe.js:3:14 at /home/kru/antphant/git/cube.js/p1/node_modules/@cubejs-backend/schema-compiler/node_modules/ramda/src/internal/_arity.js:5:45 at CubeToMetaTransformer.transform (/home/kru/antphant/git/cube.js/p1/node_modules/@cubejs-backend/schema-compiler/compiler/CubeToMetaTransformer.js:35:10)

**Comment by paveltiunov** [comment]
@krunalsabnis Hey Krunal! Seems like it was fixed in v.0.4.0.

**Comment by krunalsabnis** [comment]
@paveltiunov Yes tested and works file. Thanks !
