### ISSUE TITLE
 issue with Time Field for mongoBI

### ISSUE THREAD

**Issue by krunalsabnis** [statsbotco/cube.js#50]
While using mysql driver for mongoBI

Time fields are mapped correctly in "time" field. But when selected any of them this error is thorwn

Error: Error: scalar function 'convert_tz' is not supported

**Comment by paveltiunov** [comment]
@krunalsabnis Yep. Seems like Mongo BI connector lacks support of `convert_tz` function: https://docs.mongodb.com/bi-connector/master/supported-operations/ . We'd need to find a way to generate appropriate SQL for specific timezone.
