### ISSUE TITLE
Make API path namespace configurable

### ISSUE THREAD

**Issue by dtslvr** [statsbotco/cube.js#52]
In the official blog post [Node Express Analytics Dashboard with Cube.js](https://statsbot.co/blog/node-express-analytics-dashboard-with-cubejs) it's mentioned that 
Cube.js is
> mounted into the `/cubejs-api/v1/` path namespace. But you can change it and a lot of other things by passing the configuration object to the `CubejsServerCore.create()` method.

In the _API Gateway_ the path seems to be hardcoded (see [L196](https://github.com/statsbotco/cube.js/blob/c97e45138c9d8d2570e465426591470748cf2576/packages/cubejs-api-gateway/index.js#L196), [L235](https://github.com/statsbotco/cube.js/blob/c97e45138c9d8d2570e465426591470748cf2576/packages/cubejs-api-gateway/index.js#L235) and [L248](https://github.com/statsbotco/cube.js/blob/c97e45138c9d8d2570e465426591470748cf2576/packages/cubejs-api-gateway/index.js#L248)). Nevertheless, I like the idea to have it configurable.

**Comment by paveltiunov** [comment]
@dtslvr Hey Thomas! Nice catch! Yep. Let's add it!

**Comment by dtslvr** [comment]
Okay, I will work on it.

**Comment by dtslvr** [comment]
#53

**Comment by paveltiunov** [comment]
Fixed by #53
