### ISSUE TITLE
BigQuery?

### ISSUE THREAD

**Issue by bolismauro** [statsbotco/cube.js#60]
Hi,
first of all this project looks extremely interesting!

I was studying it and looking for BigQuery support. It is not clear to me whether using big query as db is supported or not, as the BQ is listed as supported in the home, but in the docs it is not mentioned in the `-d` option flag. Moreover, the CLI help says that valid options for that flags are

```-d, --db-type <db-type>    Preconfigure for selected database. Options: postgres, mysql, athena```

**Comment by paveltiunov** [comment]
@bolismauro Hey Mauro! Thanks for feedback! Right now BigQuery is part of enterprise offering. Working hard to open source and release it early next week. Please stay tuned.

**Comment by bolismauro** [comment]
Thanks!

**Comment by paveltiunov** [comment]
Just rolled out in 0.5.1.

**Comment by bolismauro** [comment]
Amazing! Is there a reference I can use? I don't see anything in the docs
