### ISSUE TITLE
mongobi nested field issue while filter query 

### ISSUE THREAD

**Issue by manojown** [statsbotco/cube.js#63]
**Describe the bug**
mongobi nested field issue while filter query  

**To Reproduce**
Filter query on bases of nested field . 
![Screen Shot 2019-03-31 at 11 20 28 PM](https://user-images.githubusercontent.com/24589611/55292699-930d3300-540b-11e9-9f96-cf3616feacdc.png)

**Expected behavior**
work perfectly if we wrap nested field by **backtick**
![Screen Shot 2019-03-31 at 10 40 09 PM](https://user-images.githubusercontent.com/24589611/55292814-c56b6000-540c-11e9-8cb8-5c20828839c5.png)

**Comment by paveltiunov** [comment]
@manojown Hey Manoj! Thanks for posting this! Just realized that we already have duplicate issue #56 .
