### ISSUE TITLE
Correctly handle queries to rollups without date ranges

### ISSUE THREAD

**Issue by keydunov** [statsbotco/cube.js#66]
**Describe the bug**
Rollups pre-aggregations require the dateRange to be passed. Currently, if it is not passed, the backend returns 500 internal error, but it should be 400 error with a clear message of the problem.

**To Reproduce**
1. Create a `rollup` pre-aggregations like this
```
  preAggregations: {
   main: {
     type: `rollup`,
     measureReferences: [amount],
     timeDimensionReference: createdAt,
     dimensionReferences: [Users.city],
     granularity: `day`,
     partitionGranularity: `day`
   }
  }
```
2. Send a query without date range
```
{"query":"{\"measures\":[\"Orders.amount\"],\"timeDimensions\":[{\"dimension\":\"Orders.createdAt\",\"granularity\":\"day\"}],\"dimensions\":[\"Users.city\"],\"filters\":[]}"
```

**Expected behavior**
The server should handle this case and return a User Error with a clear message.

**Version:**
0.5

**Comment by paveltiunov** [comment]
Fixed in https://github.com/statsbotco/cube.js/commit/6b399ea
