### ISSUE TITLE
Microsoft SQL Server Database Support

### ISSUE THREAD

**Issue by Ace139** [statsbotco/cube.js#76]
It can help connect to Azure SQL Database, Azure MS-SQL Server, etc.

**Comment by paveltiunov** [comment]
@Ace139 Hey Soumyo! Yep. We have MS SQL support. It's just not open sourced yet. We'll ship it soon. Please stay tuned.

**Comment by paveltiunov** [comment]
@Ace139 Hey Soumyo! Just released in v0.7.2. Could you please check and let us know if there're any issues? Thanks!

**Comment by Ace139** [comment]
Thanks a lot Pavel.

Regards,

Soumyo Dey

________________________________

**Comment by hegde89** [comment]
@paveltiunov  

we have added the following in .env file

CUBEJS_DB_HOST=<Azure DB Server >
CUBEJS_DB_NAME=<Azure DB name>
CUBEJS_DB_PORT=1433
CUBEJS_DB_USER=<Username>
CUBEJS_DB_PASS=<password>
CUBEJS_DB_DOMAIN=<unknown value>
CUBEJS_DB_TYPE=mssql
CUBEJS_API_SECRET=<data>

after run " npm dev " 

we are facing this error

Error while loading DB schema
ConnectionError: Windows logins are not supported in this version of SQL Server. at Connection.tedious.once.err (C:\Users\mbvadmin\cubejs\devcube\node_modules\mssql\lib\tedious.js:244:17) at Object.onceWrapper (events.js:286:20) at Connection.emit (events.js:198:13) at Connection.processLogin7NTLMResponse (C:\Users\mbvadmin\cubejs\devcube\node_modules\tedious\lib\connection.js:1411:14) at Connection.message (C:\Users\mbvadmin\cubejs\devcube\node_modules\tedious\lib\connection.js:1955:14) at Connection.dispatchEvent (C:\Users\mbvadmin\cubejs\devcube\node_modules\tedious\lib\connection.js:1084:36) at MessageIO.messageIo.on (C:\Users\mbvadmin\cubejs\devcube\node_modules\tedious\lib\connection.js:984:14) at MessageIO.emit (events.js:198:13) at Message.message.on (C:\Users\mbvadmin\cubejs\devcube\node_modules\tedious\lib\message-io.js:32:14) at Message.emit (events.js:203:15)

**Comment by snill93** [comment]
Hi @hegde89, did you resolved in some way the issue?

**Comment by skchauhan016** [comment]
Hello @hegde89  and @snill93 did you fond any solution?
I am facing same issue.

**Comment by Srikar9908** [comment]
we are facing a problem connecting ms SQL database

CUBEJS_DB_HOST=
CUBEJS_DB_NAME=DBNAME
CUBEJS_DB_USER=sa
CUBEJS_DB_PASS=sa@123
CUBEJS_DB_PORT=3333
CUBEJS_DB_DOMAIN=localhost
CUBEJS_DEV_MODE=true
CUBEJS_DB_TYPE=mssql
CUBEJS_API_SECRET=83f96867ecc87d5ae3c6ae11f05c460f59dcd8b4ed9db1e4e3300e2a1da5069ad2ccb88f27c54f4
CUBEJS_DB_SSL=false 



Error while loading DB schema
ConnectionError: Failed to connect to DESKTOAVCT3\SQL2017 in 15000ms at Connection.<anonymous> (C:\Users\srikar\cubedev\node_modules\mssql\lib\tedious\connection-pool.js:68:17) at Object.onceWrapper (events.js:422:26) at Connection.emit (events.js:315:20) at Connection.connectTimeout

**Comment by surajlifeean** [comment]
I am facing the same issue? Any resolution?
