### ISSUE TITLE
Mongodb BI SSL configuration broken

### ISSUE THREAD

**Issue by vladi-dev** [statsbotco/cube.js#77]
**Describe the bug**
The current implementation of `cubejs-mongobi-driver` has broken SSL connection support.
It passes ssl config to underlying `node-mysql2` driver like so:
https://github.com/statsbotco/cube.js/blob/3202508c98f7c2f342e5936b7f219d78876a2117/packages/cubejs-mongobi-driver/driver/MongoBIDriver.js#L9-L17

https://github.com/statsbotco/cube.js/blob/3202508c98f7c2f342e5936b7f219d78876a2117/packages/cubejs-mongobi-driver/driver/MongoBIDriver.js#L26

But underlying `mysql` driver used to connect to `mongo bi (mongosqld)` accepts ssl config as an object:
https://github.com/sidorares/node-mysql2/blob/b38c3a45c887a38180896c3a6f256296018511dd/lib/connection.js#L299

```
const secureContext = Tls.createSecureContext({
      ca: this.config.ssl.ca,
      cert: this.config.ssl.cert,
      ciphers: this.config.ssl.ciphers,
      key: this.config.ssl.key,
      passphrase: this.config.ssl.passphrase
    });
```

**To Reproduce**
Try configuring SSL

**Expected behavior**
SSL configuration should work.

**Version:**
[e.g. 0.4.5]

**Additional context**
Opened a PR.

**Comment by paveltiunov** [comment]
Hey @vladi-dev ! Thanks for posting this! Really comprehensive research! 👍 
I believe we have current code working in some deployments with MongoDB Atlas but seems like it's side effect of `tls.createSecureContext()` can receive empty object. So we'd need to update this stuff for sure.

Could you please elaborate a little bit on your use case? Do you want to connect to server with custom cert?

**Comment by vladi-dev** [comment]
My main use case is connecting to a `mongobi` -> `mongodb` that has authentication enabled.
I do not necessarily need to use a certificate but mongodb drops the connection when trying to authenticate without SSL.

So for `mongodb` and `mongobi`, I had to enable SSL authentication by using self-signed certs but now `cubejs` server need to validate the SSL connection with our custom certificate authority cert (ROOT CA).

With my PR I am able to connect cubejs to mongodb just by supplying `this.config.ssl.ca,` but I am sure other people might want to enable certificate checking on the mongo side so they would have to pass `this.config.ssl.cert,` as well.

Let me know if there is additional work to be done for this PR.

**Comment by paveltiunov** [comment]
@vladi-dev That totally makes sense. Added comment to PR. Thanks!

**Comment by shinebayar-g** [comment]
@vladi-dev Hello, sorry for the ping outta nowhere. Can you take a look at [here](https://github.com/cube-js/cube.js/issues/222#issuecomment-646419093)? Few folks here having a hard time.
