### ISSUE TITLE
Support for GCP Cloud Functions

### ISSUE THREAD

**Issue by tanvi-cota** [statsbotco/cube.js#87]
**Is your feature request related to a problem? Please describe.**
Currently we are having GCP cloud functions, serving our application. `cube.js` provides support to AWS Lambda. 

**Describe the solution you'd like**
Instead of going to another deployment environment like `docker`, it would be great if I can just use another GCP cloud function

**Describe alternatives you've considered**
Use another deployment environment like `docker`

**Comment by paveltiunov** [comment]
@tanvi-cota Hey Tanvi! Thanks for posting this! As many interested in this feature it's already in development. Please stay tuned.

**Comment by tanvi-cota** [comment]
@paveltiunov any idea which version will this be in?

**Comment by paveltiunov** [comment]
@tanvi-cota Hey Tanvi! Should be shipped this week or early next week.

**Comment by paveltiunov** [comment]
@tanvi-cota Hey Tanvi! Just released this in v0.8.1. Please refer to this quick start guide: https://github.com/statsbotco/cube.js/blob/master/packages/cubejs-serverless-google/README.md. It's pretty tricky to setup it so please reach me out if you have any questions.
