### ISSUE TITLE
Filter implementations of USER_CONTEXT und FILTER_PARAMS behave differently

### ISSUE THREAD

**Issue by chaselmann** [statsbotco/cube.js#88]
**Describe the bug**

The filter implementations of `USER_CONTEXT` and `FILTER_PARAMS` are not behaving as expected. 

`USER_CONTEXT.attribute.filter(expression)` accepts only character expressions
`FILTER_PARAMS.attribute.filter(expression)` accepts character expressions and functions

Passing a function parameter to the filter implementation of `USER_CONTEXT` results in an invalid sql query.

**To Reproduce**
1. Pass a function parameter to the filter implementation of `USER_CONTEXT` 

```
cube(`Orders`, {
  sql: `SELECT * FROM orders 
        WHERE ${USER_CONTEXT.email.filter((x) => 'email LIKE ${x} ')}`,

  dimensions: {
    date: {
      sql: `date`,
      type: `time`
    }
  }
});
```
2. Trigger sql generation
3. See query parsing error in console

**Expected behavior**
The filter implmentation of `USER_CONTEXT` should behave like `FILTER_PARAMS` and accept functions as parameters

**Version:**
0.7.5

**Comment by paveltiunov** [comment]
@chaselmann Hey Christoph! Thanks for posting this! It's indeed should have the same behaviour as it shares very similar concept but different implementations.
The place it should be fixed:
https://github.com/statsbotco/cube.js/blob/7961140cbd34a276cae079aff9e2e32510105f0d/packages/cubejs-schema-compiler/adapter/BaseQuery.js#L1304
Implementation of `filter()` that should be reused:
https://github.com/statsbotco/cube.js/blob/7961140cbd34a276cae079aff9e2e32510105f0d/packages/cubejs-schema-compiler/adapter/BaseQuery.js#L1329
