### ISSUE TITLE
Wrong variables when creating new BigQuery backed project

### ISSUE THREAD

**Issue by inikolaev** [statsbotco/cube.js#97]
**Describe the bug**
When creating a new project backed by BigQuery the `.env` file contains the following variables:

```
CUBEJS_DB_HOST=<YOUR_DB_HOST_HERE>
CUBEJS_DB_NAME=<YOUR_DB_NAME_HERE>
CUBEJS_DB_USER=<YOUR_DB_USER_HERE>
CUBEJS_DB_PASS=<YOUR_DB_PASS_HERE>
CUBEJS_DB_TYPE=bigquery
CUBEJS_API_SECRET=some-secret
```

Whereas  [documentation](https://cube.dev/docs/connecting-to-the-database#configuring-connection-for-cube-js-cli-created-apps) mentions that these should be used for BigQuery:

```
CUBEJS_DB_BQ_PROJECT_ID
CUBEJS_DB_BQ_KEY_FILE
CUBEJS_DB_BQ_CREDENTIALS
```

**To Reproduce**
```
cubejs create cubejs-bigquery-demo -d bigquery
cd cubejs-bigquery-demo
cat .env
```

**Expected behavior**
Only variables applicable to the selected database should be added to the `.env`, else it's confusing, especially for new users like myself.

**Version:**
0.7.6

**Comment by paveltiunov** [comment]
@inikolaev Hey Igor! Yep. It's just not implemented. I believe it worth move such env requirements on a driver level and then fetch those from CLI during install.
